apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: postgres
  template:
    metadata:
      labels:
        name: postgres
        deploy: postgres
    spec:
      restartPolicy: Always
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /mnt/blob
              name: volume
              subPath: pgdata
          env:
            - name: PGDATA
              value: /mnt/blob/pgdata/
          resources:
            limits:
              cpu: "0.8"
              memory: "1024M"
            requests:
              memory: "512M"
              cpu: ".5"
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pgs-pvc-blob