apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: postgres
  template:
    metadata:
      labels:
        name: postgres
        deploy: postgres
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /mnt/azure
              name: volume
          #volumeMounts:
          #  - name: azure
          #    mountPath: /var/postgresql
          #    subPath: pgdata
          env: 
            - name: PGDATA
              value: /var/postgresql/data
          resources:
            limits:
              cpu: "0.8"
              memory: "1024M"
            requests:
              memory: "512M"
              cpu: ".5"
      #volumes:
      #  - name: azure
      #    persistentVolumeClaim:
      #        claimName: pv-claim-postgres

      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile